// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAgR1-2u24p0wkeWI3O0jTEODjBdyqMPM',
    appId: '1:932790629611:web:db5931a0db0fe1fd85faae',
    messagingSenderId: '932790629611',
    projectId: 'auditoriumbook-854f4',
    authDomain: 'auditoriumbook-854f4.firebaseapp.com',
    storageBucket: 'auditoriumbook-854f4.firebasestorage.app',
    measurementId: 'G-STCK4MNBZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfNXPUaQF9HHhxZptVkJWVUwZWLie_3y8',
    appId: '1:932790629611:android:b3e7401fcc08406c85faae',
    messagingSenderId: '932790629611',
    projectId: 'auditoriumbook-854f4',
    storageBucket: 'auditoriumbook-854f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWV-FBft9-2sp2HukwbdDsd5HVmDc8NMg',
    appId: '1:932790629611:ios:ceac31b159ca599285faae',
    messagingSenderId: '932790629611',
    projectId: 'auditoriumbook-854f4',
    storageBucket: 'auditoriumbook-854f4.firebasestorage.app',
    iosBundleId: 'com.bookauditorium.bookauditorium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWV-FBft9-2sp2HukwbdDsd5HVmDc8NMg',
    appId: '1:932790629611:ios:ceac31b159ca599285faae',
    messagingSenderId: '932790629611',
    projectId: 'auditoriumbook-854f4',
    storageBucket: 'auditoriumbook-854f4.firebasestorage.app',
    iosBundleId: 'com.bookauditorium.bookauditorium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAgR1-2u24p0wkeWI3O0jTEODjBdyqMPM',
    appId: '1:932790629611:web:4fd391be83a7771885faae',
    messagingSenderId: '932790629611',
    projectId: 'auditoriumbook-854f4',
    authDomain: 'auditoriumbook-854f4.firebaseapp.com',
    storageBucket: 'auditoriumbook-854f4.firebasestorage.app',
    measurementId: 'G-RGM3SDSM17',
  );
}
